services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=my_database

  django:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
      - DEBUG=0
      - DB_HOST=postgres
      - DB_NAME=my_database
      - DB_USER=postgres
      - DB_PASSWORD=123
    command: bash ./start_server.sh
