# Generated by Django 5.1.2 on 2024-10-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="slug")),
                ("name", models.CharField(max_length=32, verbose_name="name")),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="color",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=128, verbose_name="text")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("in_progress", "in progress"),
                            ("finished", "finished"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="active",
                        max_length=9,
                        verbose_name="status",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date and time"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasks.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
    ]
