# Generated by Django 5.0 on 2024-11-17 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='text')),
                ('status', models.CharField(choices=[('active', 'active'), ('in_progress', 'in progress'), ('finished', 'finished'), ('questioned', 'questioned'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='active', max_length=11, verbose_name='status')),
                ('position', models.IntegerField(default=0, verbose_name='position')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
