# Generated by Django 5.1.2 on 2024-10-26 11:48

from django.db import migrations
from django.contrib.auth import get_user_model

from ..models import Group

GROUPS = [
    {"slug": "movies", "name": "Фильмы", "color": "#0000ff"},
    {"slug": "purchases", "name": "Покупки", "color": "#ff0000"},
    {"slug": "books", "name": "Книги", "color": "#ffff00"},
    {"slug": "current", "name": "Текущие", "color": "#ff0000"},
]


def insert_groups(apps, schema_editor):
    user = get_user_model().objects.get(username="nikita")
    for group in GROUPS:
        Group.objects.create(user=user, **group)


def delete_groups(apps, schema_editor):
    Group = apps.get_model("tasks", "Group")
    Group.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [("tasks", "0001_initial"), ("users", "0001_insert_users")]

    operations = [migrations.RunPython(insert_groups, delete_groups)]
