# Generated by Django 5.1.2 on 2024-10-26 11:48

from django.db import migrations

from ..models import Task

BOOKS = [
    {"text": "ГПиМРМ", "status": Task.Status.FINISHED, "children": []},
    {
        "text": "Ведьмак",
        "status": Task.Status.ACTIVE,
        "children": [
            {
                "text": "Последнее желание. Меч предназначения",
                "status": Task.Status.FINISHED,
            },
            {
                "text": "Кровь эльфов. Час презрения",
                "status": Task.Status.IN_PROGRESS,
            },
            {"text": "Владычица озера", "status": Task.Status.ACTIVE},
            {
                "text": "Крещение огнём. Башня ласточки",
                "status": Task.Status.ACTIVE,
            },
            {
                "text": "Сезон гроз. Дорога без возврата",
                "status": Task.Status.ACTIVE,
            },
        ],
    },
    {"text": "1984", "status": Task.Status.ACTIVE, "children": []},
]


def insert_tasks(apps, schema_editor):
    Group = apps.get_model("tasks", "Group")
    books = Group.objects.get(slug="books")
    for book_data in BOOKS:
        book = books.tasks.create(
            text=book_data["text"], status=book_data["status"]
        )
        for child in book_data["children"]:
            books.tasks.create(**child, parent=book)


def delete_tasks(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Task.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_insert_groups"),
    ]

    operations = [migrations.RunPython(insert_tasks, delete_tasks)]
