# Generated by Django 5.1.2 on 2024-10-26 11:48

from django.db import migrations

from ..models import Task

BOOKS = [
    {"text": "ГПиМРМ", "status": Task.Status.FINISHED, "children": []},
    {
        "text": "Ведьмак",
        "status": Task.Status.ACTIVE,
        "children": [
            {
                "text": "Последнее желание. Меч предназначения",
                "status": Task.Status.FINISHED,
            },
            {
                "text": "Кровь эльфов. Час презрения",
                "status": Task.Status.IN_PROGRESS,
            },
            {"text": "Владычица озера", "status": Task.Status.ACTIVE},
            {
                "text": "Крещение огнём. Башня ласточки",
                "status": Task.Status.ACTIVE,
            },
            {
                "text": "Сезон гроз. Дорога без возврата",
                "status": Task.Status.ACTIVE,
            },
        ],
    },
    {"text": "1984", "status": Task.Status.ACTIVE, "children": []},
]


PURCHASES = [
    {"text": "Колодки", "status": Task.Status.FAILED},
    {"text": "Кофеварка", "status": Task.Status.CANCELLED},
    {"text": "Чайник", "status": Task.Status.FINISHED},
    {"text": "Кошелёк", "status": Task.Status.QUESTIONED},
    {"text": "Новый ПК", "status": Task.Status.IN_PROGRESS},
    {"text": "Топливный фильтр", "status": Task.Status.FINISHED},
    {"text": "Кастрюля", "status": Task.Status.ACTIVE},
]


def insert_tasks(apps, schema_editor):
    Group = apps.get_model("tasks", "Group")
    books = Group.objects.get(slug="books")
    for book_i, book_data in enumerate(BOOKS):
        book = books.tasks.create(
            text=book_data["text"], status=book_data["status"], position=book_i
        )
        for child_i, child in enumerate(book_data["children"]):
            books.tasks.create(**child, parent=book, position=child_i)

    purchases_group = Group.objects.get(slug="purchases")
    for purchase_i, purchase_data in enumerate(PURCHASES):
        purchases_group.tasks.create(**purchase_data, position=purchase_i)


def delete_tasks(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Task.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_insert_groups"),
    ]

    operations = [migrations.RunPython(insert_tasks, delete_tasks)]
