# Generated by Django 5.0.7 on 2024-10-13 15:42

import django.db.models.deletion
import food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_load_food_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AddField(
            model_name='diet',
            name='calories',
            field=models.FloatField(blank=True, null=True, verbose_name='calories'),
        ),
        migrations.AddField(
            model_name='diet',
            name='carbs',
            field=models.FloatField(blank=True, null=True, verbose_name='carbs'),
        ),
        migrations.AddField(
            model_name='diet',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name='fat'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=food.models.default_date, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='protein'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('mass', 'Mass'), ('piece', 'Piece'), ('pack', 'Pack')], default='mass', max_length=5, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('color', models.CharField(max_length=7, verbose_name='color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='food.fooduser', verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='food.itemtype', verbose_name='type'),
        ),
    ]
