# Generated by Django 5.1.2 on 2024-11-04 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_record_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='is locked'),
        ),
        migrations.AlterField(
            model_name='day',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_days', to='food.fooduser', verbose_name='user'),
        ),
    ]
