# Generated by Django 5.0 on 2024-11-04 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_day_is_locked_alter_day_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='color',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_comments', to='food.fooduser', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_diets', to='food.fooduser', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item_types', to='food.fooduser', verbose_name='user'),
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item_brands', to='food.fooduser', verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='food.itembrand', verbose_name='brand'),
        ),
    ]
