# Generated by Django 5.0 on 2024-11-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_itemtype_color_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item_restaurants', to='food.fooduser', verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='food.itemrestaurant', verbose_name='restaurant'),
        ),
    ]
