# Generated by Django 5.0 on 2024-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_itemrestaurant_item_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='name'),
        ),
    ]
